CREATE TABLE Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(100) UNIQUE NOT NULL,
                       year_of_birth int CHECK (year_of_birth BETWEEN 1900 AND 2010)
);

CREATE TABLE Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title varchar NOT NULL,
                     author varchar(100) NOT NULL,
                     year_of_publication int CHECK (year_of_publication >= 1500),
                     person_id int REFERENCES Person(id) ON DELETE SET NULL
)